# Site settings
permalink: /posts/:year/:month/:day/:title/
title: Makeitopen.com : Open Source Learning
tagline: Connecting Facebook's Open Source projects
fbappid: ""
gacode: "UA-44373548-14"
description: >
  This is a series of tutorials designed to introduce React Native and its Open Source ecosystem in plain English, written alongside the building of the F8 2016 app for Android and iOS.
baseurl:
url: http://makeitopen.com
ghrepo: "facebook/makeitopen"

# Build settings
gems:
  - jekyll-feed
markdown: kramdown
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'rougeHighlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  docs:
    output: true
    permalink: /tutorials/:name/
  support:
    output: true
    permalink: /support/

sass:
  style: :compressed

color:
  # Provides colour for background of top header of homepage
  primary: "#dc6f62"
  # Provides colour for background of elsewhere on site
  secondary: "#f8f8f8"
  # A color that will work for buttons laid on top of primary colour
  light: "#4ea2ce"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#393939"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#dc6f62"
  # Text of links in the nav
  navtext: "#fff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#dc6f62"
